version: '3.5'

services:
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3309:3306"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: 'mysql-password'
      MYSQL_DATABASE: otapick_demo
    container_name: otapick_demo_db

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./src:/var/www/otapick
      - ./python/site-packages:/etc/nginx/site-packages
      - ./nginx/static:/var/www/static
      - ./nginx/conf.dev.d:/etc/nginx/conf.d
    links:
      - python
    environment:
      TZ: "Asia/Tokyo"
    container_name: otapick_demo_nginx
    ports:
      - "9000:9000"

  python:
    build: ./python
    volumes:
      - ./src:/var/www/otapick
      - ./python:/var/www
    links:
      - db
      - redis
    ports:
      - "9001:9001"
    container_name: otapick_demo_python
    command: uwsgi --ini /var/www/uwsgi.ini

  celery:
    build: ./python
    command: bash -c "./wait-for-it.sh db:3306 -- ./start-celery.sh"
    links:
      - python
      - redis
    depends_on:
      - db
    ports:
      - "9002:9002"
    tty: true
    container_name: otapick_demo_celery

  redis:
    image: redis:5.0.7
    container_name: otapick_demo_redis
    tty: true
