version: '3.5'

services:
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: 'gin-TK46'
      MYSQL_DATABASE: otapick
    container_name: otapick_db

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./src:/var/www/otapick
      - ./python/site-packages:/etc/nginx/site-packages
      - ./nginx/static:/var/www/static
    links:
      - python
    environment:
      TZ: "Asia/Tokyo"
    container_name: otapick_nginx

  python:
    build: ./python
    volumes:
      - ./src:/var/www/otapick
      - ./python:/var/www
    links:
      - db
      - redis
    ports:
      - "8001:8001"
    container_name: otapick_python

  celery:
    build: ./python
    command: bash -c "chmod 755 wait-for-it.sh start-celery.sh;./wait-for-it.sh db:3306 -- ./start-celery.sh"
    volumes:
      - ./python:/var/www
      - ./src:/var/www/otapick
    links:
      - python
      - redis
    depends_on:
      - db
    ports:
      - "8002:8002"
    tty: true
    container_name: otapick_celery

  redis:
    image: redis:5.0.7
    container_name: redis
    tty: true
