version: "3.5"

services:
  python:
    build:
      dockerfile: Dockerfile-dev
    command: uwsgi --ini /var/www/uwsgi.ini

  celery:
    build:
      dockerfile: Dockerfile-dev
    command: bash -c "./wait-for-it.sh db:3306 -- ./start-celery.sh"
    links:
      - python
      - redis
    depends_on:
      - db
    ports:
      - "8002:8002"
    tty: true
