version: "3.5"

services:
  db:
    networks:
      - proxy-network

  nginx:
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: otapick.com,www.otapick.com,admin.otapick.com
      LETSENCRYPT_HOST: otapick.com,www.otapick.com,admin.otapick.com
      LETSENCRYPT_EMAIL: otapick210@gmail.com
    networks:
      - proxy-network

  python:
    build: ./python
    command: >
      bash -c 'cron && uwsgi --ini /var/www/uwsgi.ini'
    networks:
      - proxy-network

  celery:
    networks:
      - proxy-network

  redis:
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy_network
